-- ============================================================
-- insert_canis_goiania.sql — 100 leads de Canis em Goiânia-GO
-- Execute: mysql -u crmuser -p'CrmRD@2026' crm < insert_canis_goiania.sql
-- ============================================================

INSERT INTO leads (empresa, segmento, categoria, cidade, estado, telefone, observacoes, status) VALUES
('Canil My Siberian Dogs', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99997-1747', 'Proprietária: Eliane Alves de Brito Santos. Raças: Akita, Golden Retriever, Husky Siberiano, Malamute do Alaska, Samoieda, Pug. Site: huskysiberianomydogs.com', 'novo'),
('Canil Casa D\'Ouro', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99952-7544', 'Proprietária: Cynthia Franco Sandoval Lavigne. Raças: American Bully, Rottweiler, Shih Tzu, Spitz Alemão Anão', 'novo'),
('Canil Magno\'s Bulls', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98417-5742', 'Proprietário: Flávio Magno Garcia. Raças: American Bully, Bulldog Inglês, Bulldog Francês. Desde 2004. Site: canilmagnosbulls.com.br', 'novo'),
('Canil Archangel Dogs', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99404-8404', 'Proprietário: Rennon Franklim Araujo de Oliveira. Raças: Pit Bull, Bulldog Inglês, Bulldog Francês, Spitz Alemão Anão, Yorkshire', 'novo'),
('Canil American Argus', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99255-3316', 'Proprietário: Roberto Adriano de Almeida e Silva. Raça: American Staffordshire Terrier. Site: canilamericanargus.com', 'novo'),
('Canil MR. Thor Filhotes', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99111-1417', 'Proprietário: Leandro Meireles Tavares. Raças: Basset Hound, Border Collie, Golden Retriever, Pequinês, Spitz Alemão', 'novo'),
('Canil Casa de Yasmin', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99657-8137', 'Proprietário: Alex Alves Itaboray. Raças: Basset, Beagle, Bulldog, Chihuahua, Chow Chow, Cocker, Golden, Lhasa, Maltês, Pug, Rottweiler, Schnauzer, Shih-tzu, Spitz, Yorkshire', 'novo'),
('Canil Encanto Olho D\'Água', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98196-5123', 'Proprietário: Edilson Maione da Silva. Raças: Border Collie, Dogo Argentino', 'novo'),
('Canil Rancho dos Bochechas', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99575-8020', 'Proprietárias: Jane Martins de Oliveira / Vandeir Luiz de Souza Silva. Raças: Boxer, Buldogue Campeiro, Poodle', 'novo'),
('Canil Vale do Tarumã', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99204-6513', 'Proprietário: Anicarlos de Souza Lima. Raça: Buldogue Campeiro', 'novo'),
('Canil Aguiar Bull', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99470-5954', 'Proprietária: Jeniffer Pereira de Souza. Raças: Bulldog Inglês, Bulldog Francês, Pug', 'novo'),
('Canil ABR Huangdi', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98413-6713', 'Proprietário: Christiano de Lima e Silva Melo. Raça: Buldogue Francês', 'novo'),
('Canil Santos Small Dogs', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99169-5692', 'Proprietária: Cassilda Aparecida da Costa Rodrigues. Raças: Bulldog Francês, Shih Tzu, Yorkshire', 'novo'),
('Canil Recanto dos Bulls', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99314-8018', 'Proprietária: Cristiane Rodrigues Dourado. Raças: Bulldog Francês, Dogo Argentino', 'novo'),
('Canil Family Little Angels', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99128-7872', 'Proprietária: Dayana Rocha Gondim. Raças: Bulldog Francês, Pug, Shih Tzu', 'novo'),
('Canil Solar dos Miranda', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98404-6856', 'Proprietário: Daniel Rubens Miranda. Raça: Buldogue Francês', 'novo'),
('Canil Morada dos Animais', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99283-3995', 'Proprietário: Deivson Gontijo Magalhães. Raças: Bulldog Francês, Spitz Alemão Anão', 'novo'),
('Canil Thermas Bull', 'Criador', 'canil', 'Goiânia', 'GO', '(64) 99216-0688', 'Proprietário: Eduardo Martins Marques. Raças: Chihuahua, Dobermann, Pug, Spitz Alemão', 'novo'),
('Canil Furry Children', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98604-5908', 'Proprietária: Elisangela Alves de Brito. Raças: Bulldog Francês, Husky Siberiano, Malamute do Alaska, Samoieda', 'novo'),
('Canil Crispim Frenchies', 'Criador', 'canil', 'Goiânia', 'GO', '(64) 99699-2308', 'Proprietário: Elias Junior Crispim de Souza. Raça: Buldogue Francês. Site: crispimfrenchies.com.br', 'novo'),
('Canil Niflheim', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98567-9700', 'Proprietária: Geyse Nery de Almeida. Raças: Bulldog Francês, Samoieda', 'novo'),
('Canil Dixie\'s Whenis', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98564-4545', 'Proprietária: Ivone Francisca da Costa. Raças: Bulldog Francês, Spitz Alemão', 'novo'),
('Canil Cãoração', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98555-9855', 'Proprietário: José Roberto Arrais. Raças: Bulldog Francês, Bull Terrier, Pug, Shih Tzu, Spitz Alemão', 'novo'),
('Canil Gorilazz Bull', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98483-7697', 'Proprietário: Luiz Roberto Borges Junior. Raça: Buldogue Francês', 'novo'),
('Canil Lourdes Bull', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98530-4196', 'Proprietária: Maria de Lourdes Macedo de Andrade. Raça: Buldogue Francês. Site: canilstaff.com', 'novo'),
('Canil Asgard Pals', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98299-4297', 'Proprietário: Viniccius Carneiro Marques e Silva. Raças: Bulldog Francês, Dobermann, Spitz Alemão', 'novo'),
('Canil Ettore Lemuel', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98445-3288', 'Proprietários: Rafael Maurilio Rodrigues Batista / Nicole Alves Godoi Santos. Raças: Maltês, Pug, Shih Tzu, Spitz Alemão Anão, Yorkshire', 'novo'),
('Canil Bull Vargas', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99297-2523', 'Proprietário: Rafael Willians Vargas. Raças: Bulldog Francês, Rottweiler', 'novo'),
('Canil Senepool Bulls', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99613-7729', 'Proprietário: Wagner Barbosa De Oliveira. Raça: Buldogue Francês', 'novo'),
('Canil Charlotte\'s Dogs', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98211-7962', 'Proprietário: Wilker José Silva Faleiro. Raças: Bulldog Francês, Pug, Shih Tzu, Bull Terrier', 'novo'),
('Canil Difaro', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98288-4531', 'Proprietário: Robson Daniel Flávio. Raças: Bull Terrier, Bull Terrier Miniatura. Site: canilbullterrier.com.br', 'novo'),
('Canil Casa de Pedra', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98240-0021', 'Proprietário: Marco Antônio Nogueira. Raças: Chihuahua, Pastor Belga Malinois', 'novo'),
('Canil D\'Braga Gold', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99430-9079', 'Proprietário: Rodrigo Braga de Almeida. Raça: Chihuahua', 'novo'),
('Canil Dolce Souvenir', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98233-2288', 'Proprietária: Carolina Rodrigues de Jesus. Raça: Chihuahua', 'novo'),
('Canil Lumina Chris', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99644-6005', 'Proprietário: Murilo Antunes de Castro. Raça: Chihuahua', 'novo'),
('Canil Stambowsky', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98536-7040', 'Proprietária: Marilda Machado Santos. Raça: Chihuahua', 'novo'),
('Canil Tottus La Belle', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98322-7573', 'Proprietária: Julines De Sena Faleiro. Raças: Chihuahua, Collie Pêlo Longo, Spitz Alemão', 'novo'),
('Canil Von Blummer', 'Criador', 'canil', 'Goiânia', 'GO', '(64) 99982-2133', 'Proprietário: Matheus Wohnrath Pereira. Raças: Cane Corso Italiano, Rottweiler', 'novo'),
('Canil Cani di Goyaz', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99192-3030', 'Proprietário: Myk Diego Gomes da Glória Machado. Raça: Cane Corso Italiano', 'novo'),
('Canil D\'Jaó Dachshund', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 3204-1852', 'Proprietário: Carlos David Lobo Rezende. Raça: Dachshund Standard Pêlo Curto. Site: djao.com.br', 'novo'),
('Canil Capreve', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99236-1416', 'Proprietário: Lincoln Siqueira Santos. Raças: Dobermann, Pinscher, Terrier Brasileiro', 'novo'),
('Canil Von Olivenbaum', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99934-3332', 'Proprietários: Sandro Lucio de Oliveira / Leonardo Oliveira. Raça: Dobermann. Site: canilvonolivenbaum.com.br', 'novo'),
('Canil Mariano\'s Bulls', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99991-5114', 'Proprietário: Leonardo Mariano Branquinho. Raça: Dogo Argentino', 'novo'),
('Canil Gigantes Dell Porto', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99327-1359', 'Proprietário: José Márcio Barros. Raça: Dogue Alemão', 'novo'),
('Canil Santa Luzia', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99978-1314', 'Proprietário: Tênisson de Sousa Cavalcante. Raça: Fila Brasileiro. Site: filagoiano.com.br', 'novo'),
('Canil Chão de Goyaz', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98422-2385', 'Proprietário: Alessandro Castro Bueno. Raça: Fila Brasileiro', 'novo'),
('Canil Pedra de Pirenópolis', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98230-1359', 'Proprietário: Márcio Henrique dos Santos Luz. Raça: Fila Brasileiro', 'novo'),
('Canil Dogue Russel', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98124-0166', 'Proprietário: Armando Peixoto Martins. Raça: Jack Russell Terrier. Site: doguerussel.com.br', 'novo'),
('Canil Felix e Oliveira Jacks', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98627-8024', 'Proprietário: Gustavo Félix de Sousa Oliveira. Raça: Jack Russell Terrier. Site: felixeoliveirajacks.com.br', 'novo'),
('Canil Neve Casa Grande', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99601-7474', 'Proprietária: Maria das Neves Oliveira Menezes. Raça: Jack Russell Terrier', 'novo'),
('Canil Shortlegjack', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98248-7060', 'Proprietário: Marco Luciano de Oliveira. Raça: Jack Russell Terrier', 'novo'),
('Canil Caraíbas', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99812-4753', 'Proprietário: Heitor Pires de Campos Telles. Raça: Labrador Retriever, Pastor Belga Malinois. Rod. GO 462, KM 04. Site: canilcaraibas.com.br', 'novo'),
('Canil Samvet\'s Cannis', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98143-9855', 'Proprietário: Samarony Braga Santana. Raça: Shih Tzu', 'novo'),
('Canil Ursinhos do Araujo', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99827-0509', 'Proprietária: Maria Elza de Siqueira Cotrim Araujo. Raças: Shih Tzu, Spitz Alemão, Yorkshire', 'novo'),
('Canil Triunfo Dog\'s', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99800-0052', 'Proprietária: Jackeline Vasconcelos de Matos Naves. Raça: Spitz Alemão Anão', 'novo'),
('Canil De La Mer', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98453-7400', 'Proprietária: Marcia Cordeiro. Raça: Spitz Alemão Anão', 'novo'),
('Canil Alejandro Poms', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99975-7985', 'Proprietário: Elton Alejandro de Jesus Costa. Raça: Spitz Alemão Anão', 'novo'),
('Canil Amor Maior', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99255-8712', 'Proprietária: Flávia Maria Ferreira Daude. Raça: Spitz Alemão Anão', 'novo'),
('Canil Kerber\'s Dog', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99627-5026', 'Proprietário: Nelio Kerber. Raça: Spitz Alemão Anão', 'novo'),
('Canil Lima de Sá', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98447-2366', 'Proprietários: Washington Rogério de Sá / Tiago Antônio de Lima. Raças: Spitz Alemão Anão, Spitz Alemão, Yorkshire', 'novo'),
('Canil My Poms Bear', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98409-8353', 'Proprietário: Fabiano Silva de Mesquita. Raça: Spitz Alemão Anão', 'novo'),
('Canil Recanto do Rick', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99999-3280', 'Proprietária: Luciete Caetano Nascimento. Raça: Spitz Alemão Anão', 'novo'),
('Canil Von Patrick\'s Pom\'s', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99637-3300', 'Proprietária: Patricia de Souza Garcia Spirandelli. Raça: Spitz Alemão Anão', 'novo'),
('Canil Xavier Poms', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99266-4423', 'Proprietária: Sheila Sousa Xavier da Costa. Raça: Spitz Alemão Anão', 'novo'),
('Canil A Laser dos Cães', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98218-3179', 'Proprietária: Dilza de Oliveira Santos Gontijo. Raça: Spitz Alemão', 'novo'),
('Canil Amor de Bicho', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99694-3469', 'Proprietária: Lea Regina Araujo de Sousa. Raça: Spitz Alemão', 'novo'),
('Canil Colosso GYN', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98565-5496', 'Proprietária: Teresinha de Fátima Gontijo. Raça: Spitz Alemão', 'novo'),
('Canil Dog\'s Pups Marçal', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98632-3008', 'Proprietária: Margareth Marçal dos Reis. Raça: Spitz Alemão', 'novo'),
('Canil Faon Pallas Atena', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99211-4440', 'Proprietária: Maristela Vieira Batista. Raça: Spitz Alemão', 'novo'),
('Canil Flor dos Alpes', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98166-1162', 'Proprietária: Janete Mesquita Burk. Raça: Spitz Alemão', 'novo'),
('Canil Juliana Poms', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98294-2144', 'Proprietária: Juliana Rodrigues de Almeida. Raça: Spitz Alemão', 'novo'),
('Canil Legacy Bey', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98121-9282', 'Proprietário: Jorge Alberto Silva. Raça: Spitz Alemão', 'novo'),
('Canil Primavera do Leste', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99997-5895', 'Proprietária: Leoni Rebeca Peixoto. Raça: Spitz Alemão', 'novo'),
('Canil Roccha Poms', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98100-4895', 'Proprietário: Eduardo Rocha da Mata. Raça: Spitz Alemão', 'novo'),
('Canil Pet Stop', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98193-2641', 'Proprietário: Michael Milher Saeta Belchior. Raças: Pug, Spitz Alemão', 'novo'),
('Canil Victoria Rocherr', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99384-3511', 'Proprietária: Jessica Gomes da Silva Fonseca. Raça: Spitz Alemão', 'novo'),
('Canil Bull Savage', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98416-9423', 'Proprietário: Rodrigo Alves de Oliveira. Raça: Staffordshire Bull Terrier. Site: canilbullsavage.com.br', 'novo'),
('Canil Kingstafford', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98408-6625', 'Proprietário: Diogo Egidio Ferreira Abreu. Raça: Staffordshire Bull Terrier', 'novo'),
('Canil Staffdam', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98537-0591', 'Proprietário: Daniel de Azevedo Monteiro. Raça: Staffordshire Bull Terrier', 'novo'),
('Canil Caiapo GO', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98262-8120', 'Proprietário: Marcelo Candido da Silva. Raças: Terrier Brasileiro, Whippet', 'novo'),
('Canil Andraderott', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98212-5560', 'Proprietários: Silas Andrade da Silva / Edvan Francisco de Andrade. Raça: Rottweiler', 'novo'),
('Canil Ausdauer', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99976-8851', 'Proprietário: Hélio José Perillo Vasconcelos. Raça: Rottweiler', 'novo'),
('Canil Casa do Rott Condez', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98414-7037', 'Proprietário: Alberto Oliveira Condez. Raça: Rottweiler', 'novo'),
('Canil Feitiço de Akyla', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98492-1454', 'Proprietário: Washington Luiz Dorneles. Raça: Rottweiler', 'novo'),
('Canil Guimas Rott', 'Criador', 'canil', 'Goiânia', 'GO', '(64) 99676-1653', 'Proprietário: Ricardo Silva Guimarães. Raça: Rottweiler', 'novo'),
('Canil Monalisa Garcia', 'Criador', 'canil', 'Goiânia', 'GO', '(64) 99238-8026', 'Proprietária: Delaine Garcia da Silva. Raça: Rottweiler', 'novo'),
('Canil Puro Osso', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98589-0000', 'Proprietário: Davi Barbosa Rodrigues. Raça: Rottweiler', 'novo'),
('Canil Von Lumia Noria Azuos', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98273-8504', 'Proprietário: Airon Ricardo de Souza. Raça: Rottweiler. Site: lumaadestramento.com.br', 'novo'),
('Canil Khapo Nordic Puppies', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99453-4529', 'Proprietária: Edla Maria de Souza Atalaia. Raça: Samoieda', 'novo'),
('Canil Melo Valerianus', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99267-1334', 'Proprietário: André Valeriano Ferreira Neto. Raça: São Bernardo', 'novo'),
('Canil Acza Guardian', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98100-0070', 'Proprietárias: Patrícia Guedes da Rocha / Geovana Almeida Rezende. Raças: Schnauzer Miniatura, Spitz Alemão Anão', 'novo'),
('Canil Chateau du Petit Chien', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 99181-0206', 'Proprietária: Balbina Alves Faleiro. Raça: Poodle', 'novo'),
('Canil Campina Real', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98536-3183', 'Proprietária: Wesdra Augusta. Raça: Rastreador Brasileiro. Instagram: @rastreadorbrasileiro_camp.real', 'novo'),
('Canil Kalib Pitfull', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98411-9630', 'Proprietário: Hugo Flávio Xavier Barbosa. Raça: American Pit Bull Terrier', 'novo'),
('Canil Star Terrier', 'Criador', 'canil', 'Goiânia', 'GO', '(64) 99221-3012', 'Proprietário: Eder Henrique Guerra Duarte. Raças: American Staffordshire Terrier, Terrier Brasileiro. Site: starterrier.com.br', 'novo'),
('Canil Britain Border', 'Criador', 'canil', 'Goiânia', 'GO', '(64) 99604-1744', 'Proprietária: Thais Cristina Machado Moreira. Raça: Border Collie. Site: britainborderkennel.com.br', 'novo'),
('Canil William Reis', 'Criador', 'canil', 'Goiânia', 'GO', '(62) 98576-3660', 'Proprietário: Willian Reis Lima Dias. Raças: American Bully, Bulldog Inglês, Bulldog Francês', 'novo'),
('Canil Yorkshire Goiás', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Proprietário: Tiago Antônio de Lima. Raça: Biewer Terrier', 'novo'),
('Canil Alabama', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Rua T-36, 1, Setor Bueno. Entrega filhotes vacinados com contrato registrado e pedigree', 'novo'),
('Canil São José', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Rua CP 25, s/n. Mais de 15 anos no mercado. Raças: Pinscher, Maltês, Shih Tzu, Lhasa Apso, Yorkshire', 'novo'),
('Canil Quebec Retriever', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Rua Verona, s/n, Jardim Maria Helena. Filhotes de Labrador Retriever em diversas cores', 'novo'),
('Canil Provérbios 12:10', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Rua Alameda Fragonard, 2. Raças: Pastor Belga Malinois, Pastor Alemão, Rottweiler. Adestramento de cães de guarda', 'novo'),
('Canil Lamim House Dog', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Rua Juscelino da Fonseca Ribeiro, s/n. Filhotes de companhia para crianças e idosos', 'novo'),
('Canil Quinan Ferreira', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Rua José Pedro Costa, 238, sl 8', 'novo'),
('Canil Vale do Paranã', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Rua F 4, Q 29, s/n, Faiçalville', 'novo'),
('Canil Golden Trio', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Instagram: @canilgoldentriooficial. Criador de Golden Retriever', 'novo'),
('Canil Lulu Stecca', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Av. T-1, 2610, Setor Bueno. Site: canillulustecca.com.br', 'novo'),
('Canil Bia Simon\'s', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Setor Pedro Ludovico', 'novo'),
('Canil Elisabeth', 'Criador', 'canil', 'Goiânia', 'GO', NULL, 'Jardim das Esmeraldas', 'novo');
