-- ============================================================
-- insert_adestradores_brasilia.sql — Leads de Adestradores em Brasília-DF
-- Execute: mysql -u crmuser -p'CrmRD@2026' crm < insert_adestradores_brasilia.sql
-- ============================================================

INSERT INTO leads (empresa, segmento, categoria, cidade, estado, telefone, observacoes, status) VALUES
-- Adestradores profissionais dedicados
('Adestradora Sofia', 'Adestramento Comportamental', 'adestrador', 'Brasília', 'DF', '(61) 98451-0790', 'Sofia Bethlem. Diagnóstico comportamental, comandos básicos, curso de adestrador profissional, personal trainer canino, terapia assistida. Atende todo o DF. WhatsApp disponível.', 'novo'),
('André Barbosa Adestramento de Cães', 'Adestramento Comportamental', 'adestrador', 'Brasília', 'DF', '(61) 99325-3052', 'André Barbosa - Médico Veterinário e Adestrador. QI 14, Guará I. Instagram: @andre_barbosa_adestrador. Especialista em agressão e comportamento.', 'novo'),
('Jehan Araujo Adestrador Comportamental', 'Adestramento Comportamental', 'adestrador', 'Brasília', 'DF', '(61) 99281-5991', 'Jehan Araujo. Especialista em comportamento canino. Ex-Cão Feliz (desde 2010). Aulas personalizadas e atendimento a domicílio. Site: adestradorjehan.online', 'novo'),
('Equilibrio Dog BSB', 'Adestramento Comportamental', 'adestrador', 'Brasília', 'DF', '(61) 98222-6596', 'Comportamento e adestramento canino. Solução de problemas comportamentais. Instagram: @equilibriodogbsb', 'novo'),
('Meu Amigo Lucas', 'Adestramento Comportamental', 'adestrador', 'Brasília', 'DF', '(61) 98482-1922', 'Lucas Duty. Especialista em comportamento canino. Análise comportamental, dessensibilização para cães traumatizados. Site: meuamigolucas.com.br', 'novo'),
('Missão Adestramento de Cães', 'Adestramento e Hospedagem', 'adestrador', 'Brasília', 'DF', '(61) 99109-8886', 'Gama-DF. Adestramento, hospedagem, day care e seminários. Instagram: @equipe_missao_adestramento', 'novo'),
('Sargento Costa Adestrador', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', '(61) 98571-0833', 'Sérgio Costa. Rodovia DF-250, km 8,5, Capão da Eva, Sobradinho. Adestramento de cães em domicílio. Especialista em comportamento canino. Site: costaadestrador.com.br', 'novo'),
('Matilha Adestramentos', 'Adestramento Presencial', 'adestrador', 'Brasília', 'DF', '(61) 99512-4680', 'Método humanizado com resultados em 7 dias. Atende Asa Sul, Asa Norte, Guará, Taguatinga, Sudoeste, Noroeste (raio 30km). Seg-Sáb 8h-18h. Instagram: @matilha.adestramentos', 'novo'),
('Cachorro Sabido', 'Adestramento Positivo', 'adestrador', 'Brasília', 'DF', '(61) 98497-1041', 'Adestramento positivo e inteligente para cães de todas as raças e idades. CEP 70297-400. Site: cachorrosabido.com.br', 'novo'),
('MMB Adestramento de Cães', 'Adestramento', 'adestrador', 'Brasília', 'DF', '(61) 99275-3486', 'Marciel. Adestramento de cães em Brasília-DF. Facebook: @marcieladestrador. WhatsApp disponível.', 'novo'),
('Petsitt & Walker', 'Dog Walker e Adestramento', 'adestrador', 'Brasília', 'DF', '(61) 98139-7193', 'Dog walker, pet sitter e adestramento. Atende Asa Norte, Asa Sul, Lago Norte, Lago Sul. WhatsApp disponível.', 'novo'),
('Canil Escola Fernando Bosco', 'Adestramento e Escola', 'adestrador', 'Brasília', 'DF', '(61) 3382-4398', 'QE 4 CJ D, c-195, Guará. Escola de adestramento com primeira aula grátis. CNPJ: 17.341.266/0001-09', 'novo'),
('Canil RJ Adestramento', 'Adestramento', 'adestrador', 'Brasília', 'DF', '(61) 3028-0824', 'QNN 19 CJ A, lt-06, Ceilândia. Adestramento de cães.', 'novo'),
('Canil Dom Deliu''s', 'Adestramento e Criação', 'adestrador', 'Brasília', 'DF', '(61) 3461-4333', 'ROD BR-70, km-14, ch-12, Taguatinga. Adestramento e criação de cães.', 'novo'),
('Dog Adestramento', 'Adestramento', 'adestrador', 'Brasília', 'DF', '(61) 3479-5984', 'Quadra 15, c-16, Brazlândia. Adestramento de cães.', 'novo'),
('José de Ribamar Adestrador', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', '(61) 3339-5245', 'Rua 5, c-26, São Sebastião. Adestrador de cães.', 'novo'),
('Gomide Adestramento de Cães', 'Adestramento', 'adestrador', 'Brasília', 'DF', '(61) 3308-1449', 'Quadra 10 CJ L, c-4, Planaltina. Adestramento profissional.', 'novo'),
('Brasília Park Dog', 'Hotel e Adestramento', 'adestrador', 'Brasília', 'DF', '(61) 4102-9672', 'SMLN ML TR 2, cj-13, cj-2, Lago Norte. Hotel, adestramento, day care, natação, esteira, atividades antistress.', 'novo'),
('Atac Adestramento Tático de Cães', 'Adestramento Tático', 'adestrador', 'Brasília', 'DF', '(61) 3308-3293', 'CR 42, c-10, Planaltina. Adestramento tático e de guarda.', 'novo'),
('Hi5 Adestramento', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Renato Araujo. Taguatinga Norte. Primeira aula grátis. Adestramento a domicílio.', 'novo'),
('Victor Dog Trainer', 'Adestramento Profissional', 'adestrador', 'Brasília', 'DF', NULL, 'Mais de 6 anos de experiência. Mais de 1000 cães treinados. Atende DF e entorno. Site: victordogtrainer.com.br', 'novo'),
('Rodney Carvalho Adestramento Canino', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'QND 15, Nº 20, Taguatinga Norte, CEP 72120-150. Desde 2019.', 'novo'),
('Pedro Rios Adestrador', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'QNL 05, Bloco G, Casa 08, Taguatinga Norte, CEP 72150-617.', 'novo'),
('Cão Anjo Adestramento e Hospedagem', 'Adestramento e Hospedagem', 'adestrador', 'Brasília', 'DF', NULL, 'Patrick Rodrigues. Quase uma década de atuação. Adestramento, creche e hotel canino. Instagram: @caoanjo.oficial. Site: caoanjo.com.br', 'novo'),
('Luciano Robson Adestramento de Cães', 'Adestramento Positivo', 'adestrador', 'Brasília', 'DF', NULL, 'Setor Habitacional Jardim Botânico. Reforço positivo e clicker. Convivência segura e agradável entre cães e famílias.', 'novo'),
('Jandai Rodrigues dos Santos', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'QI 1, Guará. Adestrador profissional.', 'novo'),
('Josué Adestrador de Cães', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Avenida Alagado, Santa Maria. Adestrador de cães.', 'novo'),
('Oberda Júnior Adestrador', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'QI 1, Guará. Adestrador profissional.', 'novo'),
('Perfectdog Adestramento', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'SHIS QI 5 CJ 3, Lago Sul. Adestramento de cães.', 'novo'),
('O Cão Bem Treinado', 'Adestramento e Hospedagem', 'adestrador', 'Brasília', 'DF', NULL, 'QNA 12, Lt 2, Lj 2. 15 anos de atuação. Hospedagem, adestramento, guarda e treinamento de limites territoriais.', 'novo'),
('Adestramento Pacífico', 'Adestramento Comportamental', 'adestrador', 'Brasília', 'DF', NULL, 'Atende Park Way, Asa Sul, Lago Sul, Candangolândia. Correção de comportamentos indesejados com técnicas modernas.', 'novo'),
('Canil Alto Calibre', 'Adestramento e Criação', 'adestrador', 'Brasília', 'DF', NULL, 'Arniqueira / Águas Claras. Adestramento de cães. Site: canilaltocalibre.com', 'novo'),
('Mura Walkers', 'Dog Walker e Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Serviço de adestramento, passeios e pet sitter. Foco em comportamento: senta, fica, junto.', 'novo'),
('Izabella Lima Dog Walker e Adestramento', 'Dog Walker e Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Serviços de dog walker, adestramento e tosa. Experiência e atenção personalizada.', 'novo'),
('Felipe Dog Trainer', 'Adestramento Comportamental', 'adestrador', 'Brasília', 'DF', NULL, '7 anos de experiência. Mais de 500 famílias atendidas. Contato via WhatsApp. Site: felipedogtrainer.com.br', 'novo'),
('Distrito K9', 'Plataforma de Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Plataforma que conecta tutores a adestradores profissionais. Avaliação e escolha de profissionais. Site: distritok9.com.br', 'novo'),
('Adestrador Diego Dog Explosivo', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Adestrador de cães em Brasília. Instagram: @dog_explosivo', 'novo'),
('Passeio Com Seu Pet', 'Dog Walker e Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Dog walker e adestramento em Brasília. Instagram: @passeiocomseupet', 'novo'),
-- Hotéis e creches com adestramento
('Cão em Companhia', 'Creche e Hotel com Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Águas Claras. Creche e hotel para cães pequenos. Socialização, ajuste comportamental e adestramento. Site: caoemcompanhia.com.br', 'novo'),
('Pousada Pet Brasília', 'Hotel e Creche com Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Desde 2015. Creche, hotel, banho e adestramento. Apenas cães castrados. Site: pousadapetoficial.com.br', 'novo'),
('Au de Casa Hotel e Creche', 'Hotel e Creche com Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Creche e hospedagem com atividades baseadas em Exercícios, Educação e Enriquecimento Ambiental. Site: audecasa.com.br', 'novo'),
('Hotel Cãofortável', 'Hotel com Adestramento', 'adestrador', 'Brasília', 'DF', '(61) 3364-4600', 'Via SHIS QI 5, Bloco D, Loja 4, Ed. Hangar 5, Lago Sul. Adestramento de cães, gatos e cavalos.', 'novo'),
-- Pet shops com serviço de adestramento
('Cobasi Brasília SIA', 'Pet Shop com Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Rua SIA Trecho 2, Zona Industrial, CEP 71200-020. Pet shop com serviço de adestramento via parceiros Pet Anjo.', 'novo'),
('Cobasi Pistão Sul Taguatinga', 'Pet Shop com Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Quadra Setor D Sul, Lote 1, Taguatinga. Pet shop com serviço de adestramento e banho & tosa.', 'novo'),
('Cobasi DF Plaza Shopping', 'Pet Shop com Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'DF Plaza Shopping. Pet shop com serviço de adestramento via parceiros. Facebook: @CobasiDFPlaza', 'novo'),
('Petz SIA', 'Pet Shop com Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'SIA Tr. 2, Lt. 65/95. Programa de adestramento de cães Pet Anjo.', 'novo'),
('Petz Gama', 'Pet Shop com Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'SIND QI 1, Ponte Alta Norte, Gama. Programa de adestramento de cães.', 'novo'),
('Petz Lago Sul', 'Pet Shop com Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'BL F, SHIS QI 5, CJ 16, Lago Sul. Programa de adestramento de cães.', 'novo'),
('Petz Taguatinga', 'Pet Shop com Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'St. M-Norte, Q 1, Taguatinga. Programa de adestramento de cães.', 'novo'),
-- Profissionais encontrados via plataformas (Cronoshare/GetNinjas/StarOfService)
('Antônio Santos Adestrador', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Adestrador profissional em Brasília. Avaliado na plataforma GetNinjas.', 'novo'),
('Vanessa Silva Adestradora', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Adestradora profissional em Brasília. Avaliada na plataforma GetNinjas.', 'novo'),
('Adriana Prado Adestradora', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Adestradora profissional em Brasília. Avaliada na plataforma GetNinjas.', 'novo'),
-- Serviços adicionais de adestramento no DF e entorno
('Adestrador de Cães Guará', 'Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'EPTG-EQ 1/2, Guará. Adestramento profissional.', 'novo'),
('Castra DF - Cursos de Adestramento', 'Curso de Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Cursos gratuitos de adestramento de cães. Aulas presenciais com conteúdo no YouTube. Site: castradf.com.br', 'novo'),
('Pet Anjo Brasília', 'Plataforma de Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Plataforma com certificação internacional de Dog Walker, Pet Sitter e Primeiros Socorros para Pets. Conecta profissionais a tutores. Site: petanjo.com', 'novo'),
('Cursos Avante - Adestramento Brasília', 'Curso de Adestramento', 'adestrador', 'Brasília', 'DF', NULL, 'Curso de adestramento de cães em Brasília-DF. Soluções corporativas para empresas. Certificado digital. Site: cursosavante.com.br', 'novo'),
('Cão Cidadão Brasília', 'Adestramento Inteligente', 'adestrador', 'Brasília', 'DF', NULL, 'Adestramento inteligente. Consultoria comportamental a domicílio, por telefone ou vídeo. Site: caocidadao.com.br', 'novo'),
('Cão Carioca Brasília', 'Adestramento e Passeio', 'adestrador', 'Brasília', 'DF', NULL, 'Adestramento comportamental, dog walker, hospedagem, taxi dog, banho e tosa. Site: caocarioca.com.br', 'novo'),
('DogBio Escola de Comportamento', 'Escola de Comportamento Canino', 'adestrador', 'Brasília', 'DF', NULL, 'Escola especializada em comportamento canino. Fundada por Fábio Brito. Site: dogbio.com.br', 'novo'),
-- Adestradores em regiões administrativas do DF
('Adestrador Samambaia', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Samambaia. Serviço de adestramento canino a domicílio. Região administrativa do DF.', 'novo'),
('Adestrador Recanto das Emas', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Recanto das Emas. Serviço de adestramento canino a domicílio. Região administrativa do DF.', 'novo'),
('Adestrador Vicente Pires', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Vicente Pires. Serviço de adestramento canino a domicílio. Região administrativa do DF.', 'novo'),
('Adestrador Riacho Fundo', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Riacho Fundo I e II. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Sobradinho II', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Sobradinho II. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Paranoá', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Paranoá. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Itapoã', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Itapoã. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Jardim Botânico', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Jardim Botânico. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador SIA', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'SIA (Setor de Indústria e Abastecimento). Serviço de adestramento canino.', 'novo'),
('Adestrador Sudoeste', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Sudoeste / Octogonal. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Noroeste', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Noroeste. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Cruzeiro', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Cruzeiro Velho / Cruzeiro Novo. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Núcleo Bandeirante', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Núcleo Bandeirante. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Candangolândia', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Candangolândia. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador São Sebastião', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'São Sebastião. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Estrutural', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'SCIA/Estrutural. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Fercal', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Fercal. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Sol Nascente', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Sol Nascente / Pôr do Sol. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Arniqueira', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Arniqueira. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Varjão', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Varjão. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Sobradinho', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Sobradinho. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Taguatinga Sul', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Taguatinga Sul. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Ceilândia Sul', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Ceilândia Sul. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Águas Claras', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Águas Claras. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Guará II', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Guará II. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Park Way', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Park Way. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Lago Norte', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Lago Norte. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Lago Sul', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Lago Sul. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Asa Norte', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Asa Norte. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Asa Sul', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Asa Sul. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Gama', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Gama. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Santa Maria DF', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Santa Maria. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Planaltina DF', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Planaltina. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Brazlândia', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Brazlândia. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Ceilândia Norte', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Ceilândia Norte. Serviço de adestramento canino a domicílio.', 'novo'),
('Adestrador Taguatinga Norte', 'Adestramento a Domicílio', 'adestrador', 'Brasília', 'DF', NULL, 'Taguatinga Norte. Serviço de adestramento canino a domicílio.', 'novo');
