-- ============================================================
-- leads.sql — Tabela de Leads + dados iniciais (100 leads SP)
-- Execute: mysql -u crmuser -p'CrmRD@2026' crm < leads.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS `leads` (
  `id`             INT(11)       NOT NULL AUTO_INCREMENT,
  `empresa`        VARCHAR(200)  NOT NULL,
  `segmento`       VARCHAR(100)  DEFAULT NULL,
  `cidade`         VARCHAR(150)  DEFAULT NULL,
  `telefone`       VARCHAR(30)   DEFAULT NULL,
  `email`          VARCHAR(200)  DEFAULT NULL,
  `redes_sociais`  JSON          DEFAULT NULL COMMENT '{"instagram":"url","facebook":"url","tiktok":"url","youtube":"url","linkedin":"url"}',
  `website`        VARCHAR(500)  DEFAULT NULL,
  `observacoes`    TEXT          DEFAULT NULL,
  `status`         ENUM('novo','contatado','convertido','em_negociacao','descartado') NOT NULL DEFAULT 'novo',
  `cliente_id`     INT(11)       DEFAULT NULL  COMMENT 'FK para clientes quando convertido',
  `convertido_em`  TIMESTAMP     NULL DEFAULT NULL,
  `convertido_por` VARCHAR(120)  DEFAULT NULL,
  `contatado_em`   TIMESTAMP     NULL DEFAULT NULL,
  `contatado_por`  VARCHAR(120)  DEFAULT NULL,
  `criado_em`      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `atualizado_em`  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_status`   (`status`),
  KEY `idx_empresa`  (`empresa`),
  KEY `idx_segmento` (`segmento`),
  KEY `idx_cliente`  (`cliente_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ── Dados iniciais: 100 leads segmento pet SP ──────────────

INSERT INTO `leads` (`empresa`, `segmento`, `cidade`, `website`, `observacoes`) VALUES
('Planet Dog Resort', 'Hotel Pet', 'São Paulo - Brooklin', 'http://www.planetdoghotel.com.br', 'Maior hotel para cães de SP'),
('Pet Hotel Dog Life', 'Hotel Pet', 'São Paulo - Zona Leste (Penha)', 'https://pethoteldoglife.com.br', 'Hotel 5 estrelas para cães e gatos'),
('Dog Adventure', 'Hotel/Creche', 'São Paulo', 'https://dogadventure.com.br', 'Espaço 900m² com socialização supervisionada'),
('DogResort', 'Creche/Daycare', 'São Paulo', 'https://www.dogresort.com.br', 'Daycare e creche para cachorros'),
('Day Dog', 'Creche/Hotel', 'São Paulo - Campo Belo', 'https://daydog.com.br', 'Daycare e hotel - centro de bem-estar canino'),
('Coisa de Cachorro', 'Creche/Hotel', 'São Paulo', 'https://www.coisadecachorro.com', 'Daycare em contato com natureza'),
('LovvDog', 'Creche/Hotel', 'São Paulo - Bela Vista', 'https://www.lovvdog.com.br', 'Daycare e hospedagem'),
('Dog4Fun', 'Creche/Hotel', 'São Paulo', 'https://dog4fun.com', 'Creche hotel daycare para cachorro'),
('Rex Dog Club', 'Creche', 'São Paulo', 'https://www.rexdogclub.com.br', 'Creche para cachorro'),
('Dogs da Vila', 'Creche', 'São Paulo', 'https://www.dogsdavila.com.br', 'Creche para cachorro'),
('Amigos do Zoricão', 'Hotel Pet', 'São Paulo - Zona Oeste (Lapa)', 'https://www.amigosdozorikao.com.br', 'Hotel 100% soltos desde 2012'),
('Lobbo Hotels', 'Creche/Hotel', 'São Paulo (7 unidades)', 'https://www.lobbo.com.br', '7 unidades - infraestrutura adaptada'),
('Riviera dos Cães', 'Creche/Hotel', 'São Paulo', 'https://rivieradoscaes.com.br', 'Supervisão veterinária USP'),
('Mania de Cachorro', 'Creche/Hotel', 'São Paulo', 'https://maniadecachorro.com.br', 'Creche e hotel para cachorro'),
('Clube de Cãompo', 'Hotel Pet', 'Itu - SP', 'https://clubedecaompo.com.br', '60 mil m² - chalés individuais - desde 1996'),
('Sunset Resort', 'Hotel Pet', 'Ibiúna - SP', 'https://www.sunsetresort.com.br', 'Resort com sistema leva e traz'),
('Pousada Gaia Viva', 'Hotel Pet', 'Igaratá - SP', 'https://pousadagaiaviva.com', 'Pousada exclusiva para quem viaja com cães'),
('Pousada CãoBoy', 'Hotel Pet', 'Alphaville/Osasco - SP', 'https://pousadacaoboy.com.br', '+20 anos de experiência'),
('Pinkão Pet Center', 'Hotel/Pet Shop', 'Alphaville - SP', 'https://www.pinkaopetcenter.com.br', 'Hotel fazenda + pet shop + veterinário'),
('Ideal Pet Care', 'Hotel Pet', 'São Paulo', 'https://www.idealpetcare.com.br', 'Dog hotel'),
('Parque Canino SP', 'Hotel Pet', 'São Paulo - Zona Oeste', 'http://www.parquecaninosp.com.br', 'Hotel para cachorro'),
('Hotel Para Cachorros SP', 'Hotel Pet', 'São Paulo', 'https://hotelparacachorrossaopaulo.com.br', 'Hotel para pets'),
('Good Times Pet', 'Creche', 'São Paulo - Campo Belo', NULL, '500m² com atividades de enriquecimento'),
('Sr. Chico Pet Creche', 'Creche/Hotel', 'Campinas - SP', 'https://www.srchicopet.com.br', 'Creche respeitando individualidade'),
('Pouso de Bicho', 'Creche/Hotel', 'Campinas - SP', 'https://pousodebicho.com.br', 'Hotel/creche + pet spa + pet táxi'),
('Pet Life Club', 'Creche/Hotel', 'São Paulo', NULL, '15 anos promovendo socialização'),
('Dog Club Resort', 'Hotel Pet', 'Interior SP', 'https://www.dogclubresort.com.br', 'Resort para cachorro'),
('Best Friend Pet Resort', 'Hotel Pet', 'Ribeirão Preto - SP', 'https://bestfriendpetresort.com.br', '5.000m² - maior resort pet de Ribeirão'),
('Quatropatas Hotel Pet', 'Hotel/Adestramento', 'Ribeirão Preto - SP', 'https://www.quatropatashotel.com.br', 'Hospedagem e adestramento'),
('Noblesse Pet Hotel', 'Hotel/Creche', 'Ribeirão Preto - SP', NULL, 'Hotel day care creche socialização'),
('Recreio Pet Hotel', 'Hotel Pet', 'Ribeirão Preto - SP', 'https://recreio.pet', 'Hotel para pets'),
('Espaço Pra Cachorro', 'Hotel Pet', 'Ribeirão Preto - SP', NULL, 'Hotel para cães'),
('Resort dos Cães', 'Creche/Hotel', 'Santo André - SP', 'https://www.resortdoscaes.com.br', '500m² desde 2015'),
('Pet Family ABC', 'Creche/Hotel', 'Santo André - SP', 'https://petfamilyabc.com.br', 'Atende todo ABC paulista'),
('Cão a Cão', 'Creche/Hotel/Vet', 'São Caetano do Sul - SP', 'https://www.caoacao.com.br', 'Daycare hotel walker banho vet'),
('Dog Smile', 'Creche/Hotel', 'Santo André - SP', 'https://www.dogsmile.com.br', 'Hotel e creche sem gaiolas'),
('Amor aos Pets', 'Creche/Hotel/Vet', 'Santo André - SP', 'https://amoraospets.com.br', 'Daycare hotel banho adestramento vet'),
('Cidade do Pet', 'Hotel/Creche', 'ABC Paulista - SP', 'https://www.cidadedopet.com.br', 'Hotel e creche para cachorro'),
('Riacho Grande Hotel', 'Hotel Pet', 'ABC Paulista - SP', NULL, 'Hospedagem daycare spa natação'),
('Conceito Pet Sitter', 'Pet Sitter', 'São Paulo', 'https://conceito-pet-sitter.ueniweb.com', 'Higiene medicação dog walker'),
('Helen Pet Sitter', 'Pet Sitter', 'São Paulo', 'https://www.instagram.com/best.sitter', 'Cat/Dog Sitter Dog Walker Hospedagem'),
('Viver Animal', 'Pet Sitter/Dog Walker', 'São Paulo', 'https://viveranimal.com.br', 'Pet sitter e dog walker'),
('Didi Dog Walker', 'Dog Walker', 'São Paulo', 'https://diego-dog-walker.ueniweb.com', 'Passeador de cães'),
('Pet Anjo', 'Plataforma Pet Sitter', 'São Paulo', 'https://petanjo.com', 'Plataforma certificada de cuidadores'),
('DogHero', 'Plataforma Hotel/Creche/Sitter', 'São Paulo', 'https://www.doghero.com.br', 'Maior plataforma pet do Brasil'),
('Dog Walker Brasil', 'Plataforma Dog Walker', 'São Paulo', 'https://dogwalkerbrasil.com.br', 'Conecta tutores e dog walkers'),
('Pet Sitters do Brasil', 'Pet Sitter', 'São Paulo', 'https://www.petsittersdobrasil.com.br', 'Rede de pet sitters'),
('Toma Conta', 'Plataforma Pet Sitting', 'São Paulo', 'https://www.tomaconta.com', 'Pet sitting e walking'),
('Dr. Dog', 'Adestramento', 'São Paulo (todas as zonas)', 'https://www.drdog.com.br', 'Adestramento domiciliar + curso profissional'),
('Ricardo Zanini', 'Adestramento', 'São Paulo - Brooklin/Moema', 'https://www.treinamentodecaes.com.br', '29+ anos de experiência'),
('Positidog', 'Adestramento', 'São Paulo', 'https://positidog.com.br', 'Adestramento positivo - 10 anos'),
('Disciplina Dog', 'Adestramento', 'São Paulo', 'https://disciplinadog.com.br', 'Adestramento de cães'),
('Beto Dog Trainer', 'Adestramento', 'São Paulo', 'https://www.instagram.com/betodogtrainer', 'Adestrador de cães'),
('Samir Abu Laila', 'Adestramento/Curso', 'São Paulo - Mandaqui', 'https://www.cursodeadestramento.com.br', 'Especialista em comportamento - competidor Agility'),
('Adestramento de Cães SP', 'Adestramento/Curso', 'São Paulo', 'https://www.adestramentodecaes.com.br', 'Curso profissional de adestramento'),
('Will Dogs', 'Adestramento/Passeio', 'São Paulo', NULL, 'Adestramento e passeios sócio-educativos'),
('Zago Adestramento', 'Adestramento', 'São Paulo', 'http://www.zagoadestramento.com.br', 'Adestrador profissional'),
('Garcia Dog Show', 'Adestramento', 'Campinas - SP', 'https://garciadogshow.com', '19+ anos - parcerias com hospitais vet'),
('K9 Camilla', 'Adestramento/Hotel', 'Campinas - SP', 'https://www.k9camilla.com', 'Escola de adestramento + hospedagem'),
('T-BLANK Adestramento', 'Adestramento', 'Guarulhos - SP', 'https://tblank-adestramento.com.br', 'Desde 2012 - obediência e reabilitação'),
('Canil SF', 'Canil/Adestramento', 'Campinas - SP', 'https://www.canilsf.com.br', 'Cão de guarda + adestramento + filhotes'),
('Canil Best Border Collie', 'Canil/Criador', 'São Paulo', 'https://www.canilbestborder.com.br', 'Pioneiro em Border Collie no Brasil'),
('Sophias Kennel', 'Canil/Criador', 'São Paulo', 'https://sophiaskennel.com.br', 'Um dos melhores canis de SP'),
('Canil Império Romano', 'Canil/Segurança', 'São Paulo', 'https://canilimperioromano.com.br', 'Venda e aluguel cães de guarda'),
('Cane Club Kennel', 'Canil/Criador', 'São Paulo', 'https://caneclub.com.br', 'Presa Canario e Cane Corso'),
('Paraíso dos Corsos', 'Canil/Criador', 'Franco da Rocha - SP', 'https://www.paraisodoscorsos.com.br', 'Especializado em Cane Corso'),
('Canil Mukaton', 'Canil/Criador', 'São Paulo', 'https://www.canilmukaton.com.br', 'Maltês - 20+ anos'),
('Canil Puppy Lulu Dogs', 'Canil/Criador', 'São Paulo', 'https://canilpuppyluludogs.com', 'Spitz Alemão Anão (Lulu)'),
('Canil Antony', 'Canil/Criador', 'São Paulo', 'https://canilantony.com.br', 'Micro e pequeno porte - 20+ anos'),
('DogHero Zona Sul', 'Hotel/Creche', 'São Paulo - Zona Sul', 'https://www.doghero.com.br/hotel-para-cachorro/sp/sao-paulo/zona-sul', 'Hospedagem domiciliar Zona Sul'),
('DogHero Zona Norte', 'Hotel/Creche', 'São Paulo - Zona Norte', 'https://www.doghero.com.br/hotel-para-cachorro/sao-paulo-sp/zona-norte', 'Hospedagem domiciliar Zona Norte'),
('DogHero Ribeirão Preto', 'Hotel/Creche', 'Ribeirão Preto - SP', 'https://www.doghero.com.br/hotel-para-cachorro/sp/ribeirao-preto', 'Hospedagem domiciliar Ribeirão'),
('DogHero Sorocaba', 'Hotel/Creche', 'Sorocaba - SP', 'https://www.doghero.com.br/creche-para-cachorro/sp/sorocaba', 'Creche domiciliar Sorocaba'),
('DogHero Campinas', 'Hotel/Creche', 'Campinas - SP', 'https://www.doghero.com.br/creche-para-cachorro/sp/campinas', 'Creche domiciliar Campinas'),
('DogHero Guarulhos', 'Hotel/Creche', 'Guarulhos - SP', 'https://www.doghero.com.br/creche-para-cachorro/sp/guarulhos', 'Creche domiciliar Guarulhos'),
('DogHero Osasco', 'Hotel/Creche', 'Osasco - SP', 'https://www.doghero.com.br/hotel-para-cachorro/sp/osasco', 'Hospedagem domiciliar Osasco'),
('Cronoshare Pet Sitter SP', 'Plataforma Pet Sitter', 'São Paulo', 'https://www.cronoshare.com.br/servicos/pet-sitter/sao-paulo/sao-paulo', 'Plataforma de cuidadores'),
('Cronoshare Adestradores SP', 'Plataforma Adestramento', 'São Paulo', 'https://www.cronoshare.com.br/servicos/adestradores-de-caes/sao-paulo/sao-paulo', 'Plataforma de adestradores'),
('Cronoshare Adestradores Campinas', 'Plataforma Adestramento', 'Campinas - SP', 'https://www.cronoshare.com.br/servicos/adestrador-de-cachorro/sao-paulo/campinas', 'Plataforma adestradores Campinas'),
('Cronoshare Adestradores Sorocaba', 'Plataforma Adestramento', 'Sorocaba - SP', 'https://www.cronoshare.com.br/servicos/adestrador-de-cachorro/sao-paulo/sorocaba', 'Plataforma adestradores Sorocaba'),
('Cronoshare Hotel Santo André', 'Plataforma Hotel', 'Santo André - SP', 'https://www.cronoshare.com.br/servicos/hotezinho-para-cachorros/sao-paulo/santo-andre', 'Plataforma hotéis pet'),
('Cronoshare Hotel Ribeirão', 'Plataforma Hotel', 'Ribeirão Preto - SP', 'https://www.cronoshare.com.br/servicos/hotezinho-para-cachorros/sao-paulo/ribeirao-preto', 'Plataforma hotéis pet'),
('GetNinjas Adestradores SP', 'Plataforma Adestramento', 'São Paulo', 'https://www.getninjas.com.br/familia/adestrador-de-caes/sp/sao-paulo', 'Plataforma de adestradores'),
('StarOfService Sorocaba', 'Plataforma Adestramento', 'Sorocaba - SP', 'https://www.starofservice.com.br/dir/sao-paulo/sorocaba/sorocaba/adestramento-de-caes', 'Plataforma adestradores'),
('Famyle Pet Sitter SP', 'Plataforma Pet Sitter', 'São Paulo', 'https://famyle.com/vagas/pet-sitter/sp/sao-paulo', 'Vagas de pet sitter'),
('PetBR Pet Sitter SP', 'Diretório Pet Sitter', 'São Paulo', 'https://www.petbr.com.br/guia/pet-sitter/sp/', '60+ empresas listadas em SP'),
('PetBR Adestradores SP', 'Diretório Adestramento', 'São Paulo', 'https://www.petbr.com.br/guia/adestradores/sp/', 'Guia de adestradores SP'),
('Hotel Fazenda Villa Vitta', 'Hotel Pet Friendly', 'Interior SP', 'https://www.hotelfazendavillavitta.com', 'Hotel fazenda que aceita pet'),
('Hotel Villa Charmosa', 'Hotel Pet Friendly', 'Interior SP', 'https://www.hotelvillacharmosa.com.br', 'Hotel fazenda pet friendly'),
('Patas da Casa', 'Guia Creches Pet', 'São Paulo', 'https://www.patasdacasa.com.br', 'Top 10 daycares de SP'),
('DedicaCão', 'Adestramento', 'Sorocaba - SP', NULL, 'Educação canina positiva'),
('CTC Sorocaba', 'Adestramento', 'Sorocaba - SP', NULL, 'Consultoria comportamental canina'),
('Move Canis', 'Adestramento', 'Sorocaba - SP', NULL, 'Adestramento com embasamento científico'),
('Renan Adestrador', 'Adestramento', 'São Paulo', 'https://www.renanadestramentodecaes.com.br', 'Adestrador de cães'),
('Pets da Lets', 'Pet Sitter', 'São Paulo - Jardim Paulista', 'https://www.petsit.com/pet-sitter-jardim-paulista-sao-paulo-pets-da-lets', 'Certificados comportamento felino/canino'),
('Ativesite Guia Top 10', 'Guia Hotéis Pet', 'São Paulo', 'https://ativesite.com.br/10-melhores-hoteis-para-pet-em-sao-paulo/', 'Top 10 hotéis pet SP'),
('Cronoshare Adestradores Guarulhos', 'Plataforma Adestramento', 'Guarulhos - SP', 'https://www.cronoshare.com.br/servicos/adestrador-de-cachorro/sao-paulo/guarulhos', 'Plataforma adestradores'),
('Tudo In Casa Guia ABC', 'Guia Hotel Pet', 'ABC Paulista - SP', 'http://www.tudoincasa.com.br/home/bichos-domesticos-e-cia/hotel-para-caes.html', 'Guia hotéis para cães ABC'),
('MF Rural Filhotes SP', 'Marketplace Canil', 'São Paulo', 'https://www.mfrural.com.br/produtos/3-634/caes-filhotes/sao-paulo', 'Marketplace de filhotes'),
('Criadores-Cães BR', 'Diretório Canis', 'São Paulo', 'http://br.criadores-caes.com/Criadores/Sao_Paulo.htm', 'Diretório de criadores por raça');
